version: '3.9'
name: pg-dba

services:

  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db-dockerfile
    restart: always
    shm_size: 128mb # set shared memory limit when using docker-compose
    environment:
      POSTGRES_PASSWORD: cool-postgres-course
    ports:
      - 5433:5432 # Different source port to not compete with local postgres installation
    # Uncomment the following if you really want to keep your postgres data around
    # on your disk. This will write to a local directory called 'db-data'
    # volumes:
    #   - ./db-data:/var/lib/postgresql/data 
    # Uncomment the following to change the log debug level
    # command: ["-d", "5"]
  
  notebook:
    container_name: notebook
    build:
      context: .
      dockerfile: ./docker/notebook-dockerfile
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./lessons:/home/jovyan/lessons # For development purposes

  pgadmin:
    container_name: pgadmin
    build:
      context: .
      dockerfile: ./docker/pgadmin-dockerfile
    restart: always
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=cool-postgres-course
